import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./Ejercicio1";
import { AuthProvider } from './Ejercicio2';
import { LanguageProvider } from "./Ejercicio3";
import {CartProvider} from './Ejercicio4';
import { PermissionsProvider } from "./Ejercicio5";
import { NotificationProvider } from "./Ejercicio6";
import { SettingsProvider } from "./Ejercicio7";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <SettingsProvider>
          <ThemeProvider>
            <AuthProvider>
              <LanguageProvider>
                <NotificationProvider>
                  <CartProvider>
                    <PermissionsProvider>
                      {children}
                    </PermissionsProvider>
                  </CartProvider>
                </NotificationProvider> 
              </LanguageProvider>
            </AuthProvider>
          </ThemeProvider>
        </SettingsProvider>
      </body>
    </html>
  );
}
